### ISSUE TITLE
Update Profile

### ISSUE THREAD

**Issue by ankit13jain** [CJ8664/wolfpool#17]
-Fetch the record of logged in user and implement the logic to update profile

**Comment by CJ8664** [comment]
Facing issues with drop-down/radio button

**Comment by CJ8664** [comment]
Include password/Confirm Password

**Comment by Rishabh05apr** [comment]
confirm password is implemented

**Comment by CJ8664** [comment]
University/Gender not getting saved. Can be done as an enhancement in next iteration
