### ISSUE TITLE
Join an existing plan and update its vacancy

### ISSUE THREAD

**Issue by ankit13jain** [CJ8664/wolfpool#19]

**Comment by ankit13jain** [comment]
Add the email id of the user who is joining the plan (logged in user) in the plan record

**Comment by niravjain** [comment]
Details in email: Source, destination, date, time, email addresses of others in the plan
Cool feature: Format email in such a way that Google gives option to add to calendar, else create .ical file

**Comment by niravjain** [comment]
Pass Plan ID from UI to server, on clicking JOIN button
Add current user to the plan in database
Update vacancy
Send mail to all in the Plan
Redirect to my trips

**Comment by niravjain** [comment]
* Send email to current user as well
* Redirect to my trips
