### ISSUE TITLE
Selecting the address in source and destination submits the form

### ISSUE THREAD

**Issue by ankit13jain** [CJ8664/wolfpool#48]
- Loading of page takes more time - geocoder failed due to zero_results
- after searching once if the source/destination is updated, datatable gives error : cannot reinitialize DataTable

**Comment by niravjain** [comment]
Error for 2nd point: DataTables warning: table id=resultTable - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

**Comment by niravjain** [comment]
2nd issue is resolved

**Comment by CJ8664** [comment]
Fixed the issues
